id: P003074
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:38:45.485718
source_metadata:
  id: bdr:W22361
  title: མང་རའི་ལོ་རྒྱུས
  author: ''
  volumes:
    54019e9a13e3474dabd2cc130a487468:
      image_group_id: I4836
      title: ''
      volume_number: 1
      total_pages: 352
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
