id: I0CC021C1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:53:04+00:00'
last_modified: '2022-06-07T17:23:21.245026+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22361
  title: མང་རའི་ལོ་རྒྱུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    5BE8:
      image_group_id: I4836
      title: ''
      total_pages: 352
      order: 1
      base_file: 5BE8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
